environments:
   - name: dev
     configs:
       endpoints:
           production:
               url: 'http://localhost:9091/booking'
           sandbox: 
                url : 'http://dev.sandbox.com:9091/booking'
       deploymentEnvironments:
           - displayOnDevportal: true
             deploymentEnvironment: Default
             deploymentVhost : localhost